### ISSUE TITLE
support sorting exports too

### ISSUE THREAD

**Issue by pabra** [simonhaenisch/prettier-plugin-organize-imports#10]
assume a module like this
```js
function a () {
  // do module internal stuff
}

function b () {
  var aResult = a();
  // do stuff with aResult
  return aResult;
}

function c () {
  // do something else
  return x;
}

// I would like to have these exports ordered too
export {c, b}
```

Do you think your plugin should order exports too or do you see this out of scope?

**Comment by simonhaenisch** [comment]
TypeScript doesn't have an "organize exports" feature so until that happens, this is out of scope. This plugin doesn't actually implement the sorting/organizing itself but uses the TypeScript API. There are other import-sorting projects that are more sophisticated (i. e. they implement the sorting themselves) that are probably better candidates for this (or some might even support it already).

Anyway, I would recommend you do your exports directly with the declarations, like

```ts
function a () {
  // do module internal stuff
}

export function b () {
  var aResult = a();
  // do stuff with aResult
  return aResult;
}

export function c () {
  // do something else
  return x;
}
```

Thanks for the issue!
