### ISSUE TITLE
Sorting behavior inconsistent with prettier

### ISSUE THREAD

**Issue by ShopstoryFabian** [simonhaenisch/prettier-plugin-organize-imports#100]
Prettier sorts "sub imports" case-sensitive, this plugin not. When checking for formatting issues, the produced auto format with this plugin enabled is erroneous.

Example:
Prettier sorting:
```jsx
import {
  A,
  B,
  C,
  a,
  b,
  c,
} from "...";
```

With this plugin enabled:
```jsx
import {
  a,
  A,
  b,
  B,
  c,
  C,
} from "...";
```

Prettier version: 2.8.8
Plugin version: 3.2.2

**Comment by ShopstoryFabian** [comment]
It seems to have been a version mismatch between VS Code plugin and prettier binary - `prettier --write .` outputted the correct format

**Comment by metinc** [comment]
I ran into the same problem. Could you please elaborate how you fixed this?

**Comment by simonhaenisch** [comment]
![off-on](https://github.com/simonhaenisch/prettier-plugin-organize-imports/assets/3410759/8ae834f5-2139-41a9-8a4c-59847f05c0eb)
