### ISSUE TITLE
Prettier 3 support

### ISSUE THREAD

**Issue by MarcinBorowski95** [simonhaenisch/prettier-plugin-organize-imports#103]
Any chance this plugin will have prettier 3 support update?

**Comment by simonhaenisch** [comment]
Duplicate of #95

**Comment by simonhaenisch** [comment]
Also, it's right there in the readme: https://github.com/simonhaenisch/prettier-plugin-organize-imports#prettier-3

**Comment by MarcinBorowski95** [comment]
Sorry, my mistake 😅
