### ISSUE TITLE
Bug or feature? Once I type blank line between imports, imports are sorted within that group

### ISSUE THREAD

**Issue by Filipeue** [simonhaenisch/prettier-plugin-organize-imports#105]
The results are inconsistent if blank line is present.

This formatted correctly:
```ts
import "@/global.css";

import Test from "@/components/Test";
import Test2 from "@/components/Test2";
```

But this one is correct too:
```ts
import Test from "@/components/Test";
import Test2 from "@/components/Test2";
import "@/global.css";
```

---
Either way I think only one of these should be correct to present clear consistency.

**Comment by zoontek** [comment]
@Filipeue It's a feature (in TypeScript, which this package is using)
