### ISSUE TITLE
Sorting does not work if newline between imports

### ISSUE THREAD

**Issue by povilasDadelo** [simonhaenisch/prettier-plugin-organize-imports#111]
@simonhaenisch I have noticed that if there is a newline between imports sorting doesn't work. Is this by design?

P.s. very cool plugin

**Comment by simonhaenisch** [comment]
Yes it's by design in the TypeScript API... it's a feature introduced in version 4.7, called "group-aware organize imports":

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#group-aware-organize-imports
