### ISSUE TITLE
Imports get removed on save

### ISSUE THREAD

**Issue by jamal7887** [simonhaenisch/prettier-plugin-organize-imports#113]
The import organizer removes imports from Typescript files upon saving, but only does this in some files.

**Comment by simonhaenisch** [comment]
It's a feature not a bug 😅

**Comment by andrew-boyd** [comment]
Another data point. Just had to remove this plugin that was added to our project. In our case in a .vue file component imports were being removed from the script block _even though those components are in use in the template tag_.

Before save
![Screenshot 2024-07-08 at 4 24 50 PM](https://github.com/simonhaenisch/prettier-plugin-organize-imports/assets/2946356/df2233a2-9e34-495e-8e19-30d64e485044)

After save
![Screenshot 2024-07-08 at 4 24 54 PM](https://github.com/simonhaenisch/prettier-plugin-organize-imports/assets/2946356/aa7dca8b-141a-41d2-9b13-6195e3971715)
