### ISSUE TITLE
Adding this plugin breaks github actions

### ISSUE THREAD

**Issue by pitis** [simonhaenisch/prettier-plugin-organize-imports#117]
Hello there,
I've been using this module for a long time, but now when I upgraded to prettier 3.1.0 and to 3.2.4 of this package, everything works fine but on github actions. For reference, my .prettierrc:

```javascript
{
  "semi": false,
  "singleQuote": true,
  "trailingComma": "es5",
  "plugins": ["prettier-plugin-organize-imports"]
}
```

and my github action 
```javascript
name: static checks

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm i
      - run: npm run format:check
      - run: npm run lint
```

this all worked fine before and also works fine if I remove the plugins array

**Comment by simonhaenisch** [comment]
need more info:

- which versions did you upgrade from?
- what's the error?

**Comment by simonhaenisch** [comment]
Hey sry completely lost track of this... did you get the issue resolved?
