### ISSUE TITLE
Using this plugin can be devastating for some types

### ISSUE THREAD

**Issue by cMing1997** [simonhaenisch/prettier-plugin-organize-imports#120]
When I use commands in a project to format all the files in the project over and over
It seems that `organizeImportsSkipDestructiveCodeActions` Configuring, or not configuring, doesn't make a difference.

Format commands：
```bash
  prettier --write . --config  .prettierrc.js 
```
Before formatting
```ts
const LayoutMap = new Map<string, () => Promise<typeof import('*.vue')>>();

export type Component<T = any> =
    | ReturnType<typeof defineComponent>
    | (() => Promise<typeof import('*.vue')>)
    | (() => Promise<T>);
```
After formatting
```ts
const LayoutMap = new Map<string, () => Promise<typeof import()>>();

export type Component<T = any> =
    | ReturnType<typeof defineComponent>
    | (() => Promise<typeof import()>)
    | (() => Promise<T>);
```

**Comment by simonhaenisch** [comment]
![confused guy](https://media1.tenor.com/m/pNFqGBftNHEAAAAC/nick-confused.gif)

**Comment by simonhaenisch** [comment]
Added your exact snippet as a test case and can't reproduce. Not sure what to do unless you can give more details and pin this down to exactly this plugin (i.e. works as expected without the plugin but doesn't when you add it).
