### ISSUE TITLE
import 'reflect-metadata'; Needs to be the first/top import to work

### ISSUE THREAD

**Issue by codeBelt** [simonhaenisch/prettier-plugin-organize-imports#122]
We are using [reflect-metadata](https://github.com/rbuckton/reflect-metadata) and it needs to be the first import of the application. 

Error: `Please add 'import "reflect-metadata"' to the top of your entry point.`.

It would be great if you can always put that import first. I am using `// organize-imports-ignore` to disable the sort order in that file.

**Comment by simonhaenisch** [comment]
That's a very specific feature request, I'm not gonna maintain a list of packages that need to come first 😅

You can use import grouping for this which is a feature supported since TypeScript 4.7

```ts
// needs to come first
import "reflect-metadata"

// this group of imports will be organized separately because there's an empty line to separate it
import { foo } from 'bar'
import { bar } from 'foo'
```

**Comment by codeBelt** [comment]
I didn't know about grouping... thanks. Love the package!
