### ISSUE TITLE
Unused imports starting with underscore get removed

### ISSUE THREAD

**Issue by babakfp** [simonhaenisch/prettier-plugin-organize-imports#128]
Hi 👋

![](https://github.com/simonhaenisch/prettier-plugin-organize-imports/assets/44144724/fb98712a-271c-4aab-9dae-bcf0ec50fd0f)

Without those imports I get type errors as explained here:

https://github.com/microsoft/TypeScript/issues/42873

Maybe the solution is to not delete the imports that start with the `_` character? This is used to tell the code editor to not complain about unused imports.

That's all. I just wanted to report.

**Comment by simonhaenisch** [comment]
Hm why don't you just use side-effect imports instead?

```diff
- import * as _1 from "../../../../node_modules/some-pkg"
+ import "../../../../node_modules/some-pkg"
```

**Comment by simonhaenisch** [comment]
Also are you sure you've set `organizeImportsSkipDestructiveCodeActions` option to `true` properly in your prettier config? Cause if you did, it really should not have removed those imports (it doesn't remove anything anymore, that's the point of the option).

**Comment by babakfp** [comment]
> Hm why don't you just use side-effect imports instead?
> 
> ```diff
> - import * as _1 from "../../../../node_modules/some-pkg"
> + import "../../../../node_modules/some-pkg"
> ```

I have tried this, but it doesn't work 🤷‍♂️.

> Also are you sure you've set `organizeImportsSkipDestructiveCodeActions` option to `true` properly in your prettier config? Cause if you did, it really should not have removed those imports (it doesn't remove anything anymore, that's the point of the option).

No, it's not set to `true`. I'm not sure, but I think I set it to `true` and it worked as expected.

What I know is, prefixing a variable name (etc) means that you are not going to get yelled that it's not unused. And the editor acts like it's used and everything is ok. So, I thought maybe this rule can be used here too ... (🤷‍♂️).

**Comment by simonhaenisch** [comment]
Well if you don't set it to true, this plugin will remove unused imports. Side-effect imports should never be considered unused though 🤷🏻‍♂️

Sry I can't do anything in this case since the whole organization goes through the TypeScript API. You can open an issue there about it.
