### ISSUE TITLE
I just want to format it, how do I get Eslint to not report an error

### ISSUE THREAD

**Issue by xiongzh120** [simonhaenisch/prettier-plugin-organize-imports#134]

**Comment by xiongzh120** [comment]
<img width="830" alt="image" src="https://github.com/user-attachments/assets/cc7f57f3-f41d-4672-a3b8-cc0766b4d29e">
<img width="1277" alt="image" src="https://github.com/user-attachments/assets/42b3f751-1720-4705-af1c-c1d9b4d02b2f">

**Comment by xiongzh120** [comment]
Should I remove "plugin:prettier/recommended", if not what else can I do?

**Comment by simonhaenisch** [comment]
Sorry was traveling thus the late response This question is too unspecific to help. You should at least describe the setup you have. So you're using Prettier with this plugin and run Prettier through ESLint I guess?

> I just want to format it

Then run `prettier -w <file>` not `eslint --fix <file>`.

Closing this for now until there's more info.
