### ISSUE TITLE
Update vue-tsc to v2.1 or later, it will not work correctly

### ISSUE THREAD

**Issue by glamseam** [simonhaenisch/prettier-plugin-organize-imports#135]
Update vue-tsc to v2.1 and testing fails
<img width="765" alt="v21" src="https://github.com/user-attachments/assets/cc516121-3a48-4687-9a5f-9e2be8ebf9e9">

**Comment by simonhaenisch** [comment]
Why is there a breaking change in a minor version 🥲 cc @johnsoncodehk

Thanks for the PR to fix it!

**Comment by simonhaenisch** [comment]
Released as `4.1.0` 🎉

**Comment by johnsoncodehk** [comment]
@simonhaenisch Volar/Vue language tools do not follow semantic versioning, so you need to use ~2.1.x instead of ^2.1.x.
