### ISSUE TITLE
Advertise the plugin in the list of community plugins on prettier documentation

### ISSUE THREAD

**Issue by murdos** [simonhaenisch/prettier-plugin-organize-imports#137]
I've discovered this plugin by chance, and I was wondering if you would agree to be added to the list of community plugins on https://prettier.io/docs/en/plugins.html#community-plugins to help others discover this plugin?

**Comment by simonhaenisch** [comment]
It was there for a while but it was removed a couple years ago 😢 see https://github.com/prettier/prettier/pull/9417#issuecomment-982496465
