### ISSUE TITLE
[Feature request] place "import type" after "import"

### ISSUE THREAD

**Issue by aarcangeli** [simonhaenisch/prettier-plugin-organize-imports#138]
Is it possible to place all "import type" directives after standard "import", so that it is easier to distinguish them when analyzing dependencies?

**Example:**
```typescript
import { calculateArea, PI } from './shapes';
import type { IShape } from './interfaces';
```

**Comment by simonhaenisch** [comment]
The plugin doesn't have the logic for sorting implemented itself, it just uses the TypeScript Language Service API. You'd have to raise this request in the TypeScript repo. What's supported already is that import groups (separated by empty lines) are sorted within each group, so you could do

```ts
import { calculateArea, PI } from './shapes';

import type { IShape } from './interfaces';
```

and it would stay like that.
