### ISSUE TITLE
When exports and imports are mixed, imports may be sorted last, possibly leading to errors

### ISSUE THREAD

**Issue by cuddlecake** [simonhaenisch/prettier-plugin-organize-imports#14]
Hi there,

thanks for the plugin, it's very useful.

One problem I encountered is the following scenario, where I had mixed exports and imports

```ts
export * from './a';
import * as B from './b';
export { B };
```

the plugin would reorganize this as:

```
export * from './a';
export { B }; // <----------- export before import
import * as B from './b';
```

I fixed instances of this problem in my code by always clearly separating them (and will update to the new syntax `export * as B from './b'` in the future when I upgrade TypeScript), but it's difficult to enforce for the entire team, since this is not a compile time error and will only crash at runtime.

**Comment by cuddlecake** [comment]
After checking out the source code of this plugin, I realize this is not a issue of this plugin, feel free to close this (unless there is interest in implementing a workaround by sorting exports after imports)

**Comment by simonhaenisch** [comment]
Yeah that's right, it would be an upstream issue. Just a suggestion though, you don't need to import then export if it's just for the purpose of re-exporting (i. e. you don't need `B` in this module). You can just directly export it, like

```js
export * as B from './b';
```

(see https://www.typescriptlang.org/docs/handbook/modules.html#export-all-as-x)
