### ISSUE TITLE
How to handle the import order of aliases `@`

### ISSUE THREAD

**Issue by ycjcl868** [simonhaenisch/prettier-plugin-organize-imports#17]
![image](https://user-images.githubusercontent.com/13595509/116016289-07b5fa00-a5f1-11eb-80fc-ff2fb99b6572.png)

Expected `@/*` module behind the library module.

**Comment by simonhaenisch** [comment]
This plugin doesn't do anything other than executing TypeScript's built-in `organizeImports` API. So if anything, this would be an upstream issue (feel free to open one there), but IMO this is a non-issue, since this plugin should make you forget about your import statements altogether (:

**Comment by zomars** [comment]
@ycjcl868 You can use [this plugin instead](https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports) that lets you group those imports.

**Comment by Colorfulstan** [comment]
> @ycjcl868 You can use [this plugin instead](https://www.npmjs.com/package/@trivago/prettier-plugin-sort-imports) that lets you group those imports.

Tust seems great, If only this would support vue or me having the time to fix that.
