### ISSUE TITLE
How should I use this plugin

### ISSUE THREAD

**Issue by wuzesen** [simonhaenisch/prettier-plugin-organize-imports#23]
i'm not sure how this plugin works.so i haven't ben able to use this plugin.
i just using commands `npm i prettier-plugin-organize-imports`, and then i using vscode commands `alt+shift+F`,
but it don't work,
![GIF 2021-5-26 7-03-01](https://user-images.githubusercontent.com/20244141/119579181-781e8980-bdf0-11eb-91ec-340892884d6c.gif)
So how should I use this plugin?

**Comment by simonhaenisch** [comment]
Since you closed this already, I assume you've figured out how to use this, but yeah you just need `prettier` installed as well (peer dependency) and the Prettier extension in VS Code, and set it as the formatter.

**Comment by simonhaenisch** [comment]
Probably related: https://github.com/pnpm/pnpm/issues/4700
