### ISSUE TITLE
release 2.3.0 missing lib directory

### ISSUE THREAD

**Issue by sod** [simonhaenisch/prettier-plugin-organize-imports#26]
As of package.json, only the index.js is included - https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/master/package.json#L17-L19, thus version 2.3.0 fails with `can't require ./lib/organize`

![image](https://user-images.githubusercontent.com/905328/126183530-9266bb0f-b320-440f-accc-0aaa1458871c.png)

**Comment by rbclark** [comment]
Seeing the same error in on the latest dependabot PR for 2.3.0:

<img width="994" alt="Screen Shot 2021-07-19 at 11 17 48 AM" src="https://user-images.githubusercontent.com/2308869/126184300-08be10db-8cb7-493d-ab6f-61f592ec8fb9.png">

**Comment by simonhaenisch** [comment]
Sry for the inconvenience, I just published `2.3.1` which fixes this (48b6d4adee99d803542b320679d1f6a7c7f14940).

**Comment by simonhaenisch** [comment]
Also just added a deprecation warning to `2.3.0`.

![image](https://user-images.githubusercontent.com/3410759/126221287-df2ce63b-2503-4f5e-a9b9-9f698c112d16.png)
