### ISSUE TITLE
Importing react at tsx files gets removed

### ISSUE THREAD

**Issue by EduardoAraujoB** [simonhaenisch/prettier-plugin-organize-imports#29]
the same as #24 
I'm just reporting it because I have the same problem and I can share my tsconfig

![Screenshot from 2021-08-04 13-55-07 (1)](https://user-images.githubusercontent.com/42449213/128223083-2cd92134-ef2d-4d59-8f31-c68f6a441536.png)

as you can see, there isn't Typescript errors, just prettier one, which I think it's related to this project

my ts config:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "noUnusedLocals": false,
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
    "baseUrl": "src",
    "noFallthroughCasesInSwitch": true,
    "noImplicitAny": false,
    "downlevelIteration": true
  },
  "include": ["src"]
}

```

**Comment by simonhaenisch** [comment]
Hi, can you try adding

```
"jsxFragment": "React.Fragment"
```

to the compiler options?

**Comment by simonhaenisch** [comment]
On second thought, the suggestion in your screenshot comes from the Prettier **ESLint** plugin and not from this **Prettier** plugin. This plugin does not contribute anything to linting, so you'll have to search elsewhere for solutions if the above doesn't help.
