### ISSUE TITLE
.vue file with <script> is "fixed" with a lot of "//"

### ISSUE THREAD

**Issue by vvalencia-cl** [simonhaenisch/prettier-plugin-organize-imports#30]
The problem only happens when I have javascript code inside <script></script>

The linter output is like this:

```
error: Insert `//⏎//⏎//⏎//⏎//⏎//⏎⏎` (prettier/prettier)
```

But works ok when the code is inside <script lang="ts"></script>

I'm attaching a screenshot of a diff after applying the plugin

![Screenshot from 2021-08-13 16-30-44](https://user-images.githubusercontent.com/1178505/129415529-3b3b2ac2-87ce-4ca6-b466-b4bb5a3a99fb.png)

Versions: 
"prettier-plugin-organize-imports": "2.3.3"
"vue": "2.6.14"
"babel-eslint": "10.1.0"
"eslint": "^6.7.2"
"eslint-plugin-prettier": "^3.3.1"
"eslint-plugin-vue": "^6.2.2"
"prettier": "2.3.2"

**Comment by simonhaenisch** [comment]
Hi thanks for reporting this, I fixed a similar issue recently with `lang=ts` script blocks and was hoping it would also work for JS, but apparently not. Will hopefully have some time soon to look into this but can't promise anything.

**Comment by Zclhlmgqzc** [comment]
Vue3 doesn't have this problem
bug for vue2
when removed @vue/compiler-sfc

```
test('Vue2 files', (t) => {
const code = `
<script>
import a from "./a";

</script>
`;

const formattedCode = prettify(code, { filepath: 'file.vue' });

t.is(formattedCode,
`<script>
//
</script>
`);
});
```

**Comment by simonhaenisch** [comment]
Thanks for the update and PR, will check it out later!
