### ISSUE TITLE
Can we adhere to tslint rule or have similar config?

### ISSUE THREAD

**Issue by Colorfulstan** [simonhaenisch/prettier-plugin-organize-imports#32]
I was trying this plugin and it seems to only order imports by a default ordering (alphabetized)

In tslint we can configure code blocks and ecplicite ordering.
See https://palantir.github.io/tslint/rules/ordered-imports/

This is useful if you have mandatory ordering on some, but not all imports.

Can this be setup already and im just not aware on how, or is this a feature request?

**Comment by Colorfulstan** [comment]
Related to #25?

**Comment by simonhaenisch** [comment]
Yeah same reason as in #25, and as I said there, in my experience you'll basically stop looking at the import statements eventually (at least if your editor support auto-imports), and you won't even care about the order anymore.

In other words, zero-config is something I want to keep up with this project. If you really care about import order and want to customize it, you'll just have to look for a different plugin.
