### ISSUE TITLE
Support for typescript path aliases

### ISSUE THREAD

**Issue by danielpza** [simonhaenisch/prettier-plugin-organize-imports#33]
Hello, great plugin. I think this is more of a feature request than a bug, but when using typescript path aliases it organizes the global imports from inside the project first than the node_modules global imports.

Expected sorting

- global node_modules imports
- global project imports (defined by path aliases)
- relative imports

But with path aliases (depending on the configuration), global project imports will appear first before the node_modules imports. Right now there's no distinction between global node_modules and global project imports.

tsconfig.json:

```json
{
  "baseUrl": "./",
  "paths": { "@/*": ["./src/*"], },
}
```

file system:

```
.
├── src
│   ├── app.js
│   ├── components
│   │   ├── Button.js
│   │   └── Home.js
│   └── shared
│       ├── log.js
│       └── utils.js
└── tsconfig.json
```

Home.js expected order:

```js
import React from 'react';
import { log } from '@/shared/log';
import Button from './Button';
```

Instead the result is:

```js
import { log } from '@/shared/log';
import React from 'react';
import Button from './Button';
```

`@/shared/log` will be aliased after compilation to `../shared/log`, so I expect it to be after `react` which is a node_module import

**Comment by danielpza** [comment]
Actually I realize this is an issue upstream on typescript, https://github.com/microsoft/TypeScript/issues/30456

**Comment by simonhaenisch** [comment]
Afaik TypeScript doesn't care at all where the import comes from, it just sorts them alphabetically? TBH I also **really** don't care about the order, I usually don't even look at the import statements anymore... so I couldn't care less how exactly they are sorted, as long as it's consistent (i. e. doesn't cause any merge conflicts/weird git diffs).
