### ISSUE TITLE
Does it not work with pnpm? :thinking: 

### ISSUE THREAD

**Issue by Shinigami92** [simonhaenisch/prettier-plugin-organize-imports#34]
I'm not sure if there is a problem on my side or if it doesn't really work anymore since I switched a project to use `pnpm` instead of `yarn`  

Also I'm not sure if this is then a bug of `prettier-plugin-organize-imports`, `prettier` or `pnpm` :thinking:

**Comment by jjlorenzo** [comment]
I'm using a workaround that probably works for you
``` js
module.exports = {
  plugins: [require.resolve("prettier-plugin-organize-imports")],
  ...
}
```
