### ISSUE TITLE
[Feature request] Support Vue SFCs with setup

### ISSUE THREAD

**Issue by ztiromoritz** [simonhaenisch/prettier-plugin-organize-imports#40]
I like the very slim approach of this lib.

I tried to use it in a Vue 3 project with `<script setup>` tags, but they are not recognised.  
It would be nice to have support for them, too.

**Comment by ztiromoritz** [comment]
I created a pull request to support this feature. https://github.com/simonhaenisch/prettier-plugin-organize-imports/pull/41

**Comment by Shayan-To** [comment]
I would love to see this feature added.

**Comment by Shinigami92** [comment]
I also now need this feature :)

**Comment by simonhaenisch** [comment]
hey there, please try out version 3.0.0

**Comment by Shinigami92** [comment]
YES, its working!
