### ISSUE TITLE
TypeScript 4.5 

### ISSUE THREAD

**Issue by httpete** [simonhaenisch/prettier-plugin-organize-imports#42]
https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

Now you can have type modifiers on import names, really nice and less imports. Would be nice to stay up with TS 4.5 and support this.

**Comment by simonhaenisch** [comment]
Typescript is a peer dependency, so what's stopping you from using it?

**Comment by httpete** [comment]
@simonhaenisch you are right. If anyone else finds this thread, after updating to TS 4.5 you have to restart the TS server in vscode in order for the red underlines go away on the new import syntax. This has nothing to do with p-p-o-i.
