### ISSUE TITLE
Conflict with other Prettier plugins, specifically prettier-plugin-tailwind

### ISSUE THREAD

**Issue by denis-sokolov** [simonhaenisch/prettier-plugin-organize-imports#44]
When used with prettier-plugin-tailwind, this plugin does not organize imports. There is an [issue open in prettier-plugin-tailwind](https://github.com/Acidic9/prettier-plugin-tailwind/issues/23). It seems to be a limitation in Prettier plugin API.

Hopefully this issue helps someone understand their problem. Perhaps add a mention of this to Readme?

**Comment by simonhaenisch** [comment]
Hm apparently I misunderstood how Prettier loads plugins... yeah doesn't seem like it can be fixed.

I'll add an info to the readme about this behavior.

**Comment by pwespi** [comment]
Related to https://github.com/tailwindlabs/prettier-plugin-tailwindcss/issues/26, which also contains a workaround to make this plugin work with `prettier-plugin-tailwindcss`.

**Comment by chalkygames123** [comment]
@denis-sokolov Thank you, I spent a whole day trying to figure out what was going on and finally got here.

For those looking for an easy solution, I would recommend [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss) as a more comprehensive alternative.
