### ISSUE TITLE
[Feature Request]: Sort order configuration 

### ISSUE THREAD

**Issue by ItaiEsquare** [simonhaenisch/prettier-plugin-organize-imports#47]
There are cases when an import must be on top. For example, in my project,`'jest-preset-angular/setup-jest'` must be on top, otherwise  testing doesn't work.
The only way to prevent this is to use `// organize-imports-ignore`, which ignores the whole file and needs to be added manually.
Adding  configuration  similar to this would be preferable: https://github.com/trivago/prettier-plugin-sort-imports#importorder

**Comment by simonhaenisch** [comment]
Basically the same as #46, please see my answer there. TL;DR: this plugin doesn't really work for that use-case, it's for projects with side-effects free imports, or where side-effect imports are isolated into helper modules.
