### ISSUE TITLE
Buggy experience with vscode formatOnSave + codeactions

### ISSUE THREAD

**Issue by johnnyasantoss** [simonhaenisch/prettier-plugin-organize-imports#48]
It may not be the scope of this project, but I'm just reporting it, so you may judge if it makes sense to fix it.

I think that vscode doesn't expect the formatting to change the file (that much), so it breaks.

## Repro

- Add `.vscode/settings.json`
```jsonc
{
  "editor.formatOnSave": true,
  "editor.formatOnSaveMode": "modificationsIfAvailable",
  "editor.codeActionsOnSave": {
    // this can be true or false there are bugs with and without it.
    "source.organizeImports": true,
    "source.fixAll": true
  },
}
```
- Add a JS file with imports and hit `ctrl + s`

I had to uninstall it because it was removing all imports.

**Comment by simonhaenisch** [comment]
Hey, `source.organizeImports` has nothing to do with this plugin, but invokes the built-in action of VS Code (i. e. what you get when you open command palette, then search for "Organize Imports"), which also works without the plugin being installed.... the plugin is just a way of hooking that action into Prettier instead.

Afaik, VS Code schedules formatters and code actions on save consecutively, so they wouldn't override each other. I'm not sure why exactly your imports were removed, but doing formatting + fixing + organizing imports on save doesn't seem to make too much sense to me. In this case it's probably best to hook Prettier into the linter, disable `formatOnSave` and only run `source.fixAll` on save.
