### ISSUE TITLE
Using multiple plugins that use typescript and babel parser.

### ISSUE THREAD

**Issue by wdfinch** [simonhaenisch/prettier-plugin-organize-imports#50]
Hi there,

I'm developing my own prettier plugin to organize JS/TS class members. I use this plugin and love it, but I noticed this line in the docs.

> This plugin inherits, extends and overrides the built-in Prettier parsers for babel, babel-ts, typescript and vue, i. e., it's incompatible with other plugins that do the same... so only the last loaded plugin that exports one of those parsers will function.

I also override the built-in Prettier parsers for typescript and babel parser to do my manipulation. I'm wondering if there is any way I can modify my code to work with this plugin. I'm new to developing these plugins so I would I really appreciate any advice on how I can make mine work with this one at the same time.

From the docs, it looks like you can run prettier and select with plugins you want to use. Therefore, you could run mine manually this way.  

`prettier --write src --no-plugin-search --plugin=my-plugin-that-conflicts`

**Comment by simonhaenisch** [comment]
Hey I think what you could do is set a plugin list manually (i think you can also configure them via `plugins` option in .prettierrc/equivalent), which then disables the auto-loading of this plugin. Then you import the parsers from this plugin and wrap them in your own custom plugin.

```js
const { parsers: organizeImportsParsers } = require('prettier-plugin-organize-imports');

const myCustomParser = (code, options) => {
 // do the things

  return customizedCode;
}

exports.parsers = {
  typescript: (code, options) => myCustomParser((organizeImportsParsers.typescript(code, options)), options),
  // ... equivalent for babel parser
};
```

Let me know if that works, would be good to know (:

**Comment by wdfinch** [comment]
Hey thanks for the advice. The only problem is my plugin is open source and therefore I can't assume that people will be using your plugin and mine together. Is there any solution like this that would work generically without making that assumption other than just checking for every possible plugin that could conflict? 

Additionally is there some solution like this that could be implemented outside the plugin via the prettier CLI or config?

So far the best I've found is to just run prettier again choosing your plugins manually in cases where you have conflicts. It'd be nice if I could run it all the plugins in one go.

**Comment by simonhaenisch** [comment]
Ok I think I misunderstood you, I thought you were talking about a project-specific custom plugin, not another publicly available one. Yeah for that problem I don't think there's a solution really other than what you already said about double-running prettier with different plugin lists, or people manually chaining the plugins like above, via a custom plugin in their project.

Since the Prettier team doesn't consider this plugin a valid use case for the plugin API, I don't have much hope that anything will change that makes plugins like this more compatible.

**Comment by wdfinch** [comment]
Makes sense. Thanks for the advice.
