### ISSUE TITLE
Keeps removing React import which is needed for JSX

### ISSUE THREAD

**Issue by patotoma** [simonhaenisch/prettier-plugin-organize-imports#54]
It keeps removing React import which is needed for JSX.

Build is then failing with error:

```
ReferenceError: React is not defined
```

There were some previously opened issues without any resolution:
https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/24
https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/29

**Comment by patotoma** [comment]
I'm using Gatsby and for me changing `tsconfig.json` compilerOptions -> jsx to from `preserve` to `react` fixed this.

**Comment by simonhaenisch** [comment]
> There were some previously opened issues without any resolution

In https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/24#issuecomment-848801729 I've basically proposed exactly what you did, and the issue only got closed several months later, assuming that the given solution was sufficient.

Anyway, glad you figured it out.

**Comment by valyagolev** [comment]
could you please add this to the readme? i spent quite some time on this issue today

**Comment by simonhaenisch** [comment]
Sure, could add that, but I'm not very familiar with which `jsx` options work or don't, so I'd have to try out some stuff first.
