### ISSUE TITLE
Vue - plugin removes imports if components are kebap-cased

### ISSUE THREAD

**Issue by linkurzweg** [simonhaenisch/prettier-plugin-organize-imports#59]
Hello, unfortunately there seems to be a bug currently when imported components are written in kebap case in Vue SFC templates. The plugin falsely recognizes them as unimported and removes them.

This works fine:
```
<template>
  <div>
    <NDivider />
  </div>
</template>

<script setup lang="ts">
  import { NDivider } from 'naive-ui'
</script>
```

This doesn't:
```
<template>
  <div>
    <n-divider />
  </div>
</template>

<script setup lang="ts">
  import { NDivider } from 'naive-ui'
</script>
```

Both are valid template syntax. 
A fix would be greatly appreciated. Thanks a lot for developing this plugin :)

**Comment by simonhaenisch** [comment]
Hm ok that's some very implicit behaviour right there. I'm not a Vue user myself so I can't give much support regarding that for this plugin, however for Vue it uses `@volar/vue-typescript`'s language service API to run `source.organizeImports`, which means there's nothing I can do about it here anyway. Could you please raise the issue in the [Volar](https://github.com/johnsoncodehk/volar) repo, and we can leave it open here until it's fixed there.
