### ISSUE TITLE
Version 3.0.1 leads to false parsing errors in Vue 2

### ISSUE THREAD

**Issue by Santobert** [simonhaenisch/prettier-plugin-organize-imports#66]
Version 3.0.1 causes parsing errors like the following:

- Parsing error: Unexpected closing tag "td"
- Parsing error: Unexpected closing tag "script"
- Parsing error: Unexpected closing tag "div"
- Parsing error: Unexpected character "EOF"

In my project, almost every Vue file with a template section contains exactly one of these errors. However, the files are fine. As soon as I remove or downgrade `prettier-plugin-organize-imports`, the errors are gone and everything works as expected.

I use the following setup, which is more or less the exact setup that every newly created vue 2 project has:
```json
...
"dependencies": {
  ...
  "vue": "2.7.8",
  ...
},
"devDependencies": {
  "@rushstack/eslint-patch": "1.1.4",
  ...
  "@types/node": "18.6.3",
  "@vitejs/plugin-vue2": "1.1.2",
  "@volar/vue-typescript": "0.39.4",
  "@vue/eslint-config-prettier": "7.0.0",
  "@vue/eslint-config-typescript": "11.0.0",
  "@vue/tsconfig": "0.1.3",
  "eslint": "8.21.0",
  "eslint-plugin-vue": "9.3.0",
  "npm-run-all": "4.1.5",
  "prettier": "2.7.1",
  "prettier-plugin-organize-imports": "3.0.1",
  "typescript": "4.7.4",
  "vite": "3.0.4",
  "vue-tsc": "0.39.4"
}
```

**Comment by simonhaenisch** [comment]
Thanks for the issue, could you be more specific about the before/after output? Or if you could provide a test case that would be even better (: I'll probably need to forward this to @johnsoncodehk because it's most likely a problem with `@volar/vue-typescript`.

**Comment by Santobert** [comment]
You can find a minimal example here: https://github.com/Santobert/prettier-plugin-organize-imports-issue

## Steps to recreate this example

1. Run `npm init vue@2` as stated here to create a Vue 2 project with a modern toolchain
2. Select `TypeScript: yes`, `JSX: no`, `Vue Router: no`, `Pinia: no`, `Vitest: no`, `Cypress: no`, `ESLint: yes`, `Prettier: yes`
3. Run `cd vue-project` and `npm install`
4. Run `npm i --save-dev @volar/vue-typescript prettier-plugin-organize-imports` to install prettier-plugin-organize-imports
5. Run `npm run lint` and see the following warnings

```
> npm run lint

> vue-project@0.0.0 lint
> eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore

...\vue-project\src\App.vue
  4:2  warning  Parsing error: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags  prettier/prettier

...\vue-project\src\components\TheWelcome.vue
  8:2  warning  Parsing error: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags  prettier/prettier

✖ 2 problems (0 errors, 2 warnings)

```

**Comment by simonhaenisch** [comment]
Hm I can't reproduce this 🤔  I cloned your repo, ran `npm i` and then `npm run lint` and there's no errors/warnings and the files look fine.

Are you using a not so recent Node version by any chance?

**Comment by simonhaenisch** [comment]
I initially used Node 18.7 but just tried with Node 12.22 and seems fine as well 🤷🏻‍♂️

Anyway, can you give me some more info about your platform? Node version, OS, user-level Prettier config (e.g. `~/.prettierrc`), etc?

**Comment by Santobert** [comment]
I'm on Windows 10 and I've tried Node 16.x (LTS) and Node 18.x (the current version). The error occurs in my sample project even without `.prettierrc`, so it seems to be independent of the prettier configuration or at least it happens with the default values.
I'll try to reproduce the issue with a different computer today...

**Comment by Santobert** [comment]
Another update: The issue also occurs with Vue 3:

```powershell
PS C:\Users\tobia\git> npm init vue@latest
Need to install the following packages:
  create-vue@3.3.1
Ok to proceed? (y) y

Vue.js - The Progressive JavaScript Framework

√ Project name: ... vue-project
√ Add TypeScript? ... No / Yes
√ Add JSX Support? ... No / Yes
√ Add Vue Router for Single Page Application development? ... No / Yes
√ Add Pinia for state management? ... No / Yes
√ Add Vitest for Unit Testing? ... No / Yes
√ Add Cypress for both Unit and End-to-End testing? ... No / Yes
√ Add ESLint for code quality? ... No / Yes
√ Add Prettier for code formatting? ... No / Yes

Scaffolding project in C:\Users\tobia\git\vue-project...

Done. Now run:

  cd vue-project
  npm install
  npm run lint
  npm run dev

PS C:\Users\tobia\git> cd .\vue-project\
PS C:\Users\tobia\git\vue-project> npm install

added 258 packages, and audited 259 packages in 1m

71 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\tobia\git\vue-project> npm install --save-dev prettier-plugin-organize-imports @volar/vue-typescript

added 7 packages, changed 4 packages, and audited 266 packages in 3s

71 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\tobia\git\vue-project> npm run lint

> vue-project@0.0.0 lint
> eslint . --ext .vue,.js,.jsx,.cjs,.mjs,.ts,.tsx,.cts,.mts --fix --ignore-path .gitignore


C:\Users\tobia\git\vue-project\src\App.vue
  4:2  warning  Parsing error: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags  prettier/prettier

C:\Users\tobia\git\vue-project\src\components\TheWelcome.vue
  8:2  warning  Parsing error: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags  prettier/prettier

✖ 2 problems (0 errors, 2 warnings)

PS C:\Users\tobia\git\vue-project>
```

**Comment by Santobert** [comment]
Last update for now:
The problem seems to occur only on Windows machines. I could not reproduce this problem on Linux.

**Comment by simonhaenisch** [comment]
Hey, could you please try out version `3.0.2` whether it fixes this? The implementation of `getScriptSnapshot` in the language service host was incorrect, and maybe the fix also fixes your issue. Thanks!

**Comment by Santobert** [comment]
Unfortunately, the issue stays with the latest version 3.0.2

**Comment by simonhaenisch** [comment]
Ok, unfortunately I also don't have a Windows machine to debug this :/

Can you maybe try opening `node_modules/prettier-plugin-organize-imports/lib/service-host.js` and comment out lines 19 (`fileExists`) and 24 (`readFile`)?

Otherwise you can check the diff for [v3.0.0..v3.0.1](https://github.com/simonhaenisch/prettier-plugin-organize-imports/compare/v3.0.0..v3.0.1) for other things that have changed and try reverting them, maybe try downgrading `@volar/vue-typescript` to `0.37.9`, and change [this code](https://github.com/simonhaenisch/prettier-plugin-organize-imports/compare/v3.0.0..v3.0.1#diff-ceb5c0a234b47fa6871a8140f5c29f4120b28ca348ab5acb5cd9682c8ffba7eaL28-L34) back.

Would appreciate the help... otherwise it'll be a while until I can get to a Windows machine.

**Comment by Santobert** [comment]
Reverting vue-typescript to 0.37.9 and changing back the given parts (this code) somehow did the trick. Even though I've no idea, what I've done, it somehow worked.

**Comment by simonhaenisch** [comment]
Ok cool thanks for confirming... I think I'll have to redirect you to https://github.com/johnsoncodehk/volar then, to open an issue there about the recent versions of `@volar/vue-typescript` not working correctly on Windows.

**Comment by Santobert** [comment]
It seems there is already an issue opened: https://github.com/johnsoncodehk/volar/issues/1670#issue-1328117598
