### ISSUE TITLE
Huge performance regression in 3.0.2

### ISSUE THREAD

**Issue by danewilson** [simonhaenisch/prettier-plugin-organize-imports#67]
This is affecting all of our packages, but as an example the prettier runtime has gone from 6.35s to 489.94s in one package, and that's one of our smaller packages. The runtime for our larger packages is in the hours.

**Comment by simonhaenisch** [comment]
Thanks, I'm on it, hopefully able to fix today.

**Comment by simonhaenisch** [comment]
Just released `3.0.3` which should fix this, can you please confirm?

I was already wondering why the tests were timing out in the CI and I had to increase the timeout 😅

**Comment by danewilson** [comment]
Seems to be resolved, thanks for the quick turnaround.

**Comment by askielboe** [comment]
Resolved for us as well. Thanks!
