### ISSUE TITLE
Vue PascalCase components get removed while using pug templates

### ISSUE THREAD

**Issue by Shinigami92** [simonhaenisch/prettier-plugin-organize-imports#68]
Since v3.0.1 (worked in v3.0.0)

Please checkout: https://github.com/Shinigami92/quasar-vite/tree/orgi-imports-bug-1 (it's a branch)
Run:
- pnpm install
- pnpm run format
- See issue in LoginPage.vue that PasswordInput.vue got removed but still used in the pug template below

/cc @johnsoncodehk Were there any huge related changes in Volar ecosystem that raised these bugs? (like also #64, #67)

**Comment by johnsoncodehk** [comment]
I think the repo missing `@volar/vue-typescript` for `prettier-plugin-organize-imports`, and missing `@volar/pug-language-service` for `@volar/vue-typescript` + `vue-tsc`.

**Comment by Shinigami92** [comment]
> I think the repo missing `@volar/vue-typescript` for `prettier-plugin-organize-imports`

But `@volar/vue-typescript` is a sub-dependency of `vue-tsc`

```node
> pnpm why @volar/vue-typescript
Legend: production dependency, optional only, dev only

my-view-frontend@1.0.0-alpha.1 /Users/shinigami/Dermalog/frontend

devDependencies:
vue-tsc 0.39.5
└── @volar/vue-typescript 0.39.5
```

**Comment by Shinigami92** [comment]
@simonhaenisch Still occurs with v3.0.3

**Comment by simonhaenisch** [comment]
BTW #64 and #67 have both been fixed and were completely unrelated to this, they weren't even about Vue.

You can try manually undoing some of the changes from [v3.0.0..v3.0.1](https://github.com/simonhaenisch/prettier-plugin-organize-imports/compare/v3.0.0..v3.0.1), maybe try downgrading `@volar/vue-typescript` to `0.37.9`, and change [this code](https://github.com/simonhaenisch/prettier-plugin-organize-imports/compare/v3.0.0..v3.0.1#diff-ceb5c0a234b47fa6871a8140f5c29f4120b28ca348ab5acb5cd9682c8ffba7eaL28-L34) back.

It's most likely an issue related to the changes in `@volar/vue-typescript`.

**Comment by Shinigami92** [comment]
I assumed that it has something to do with the "missing" `@volar/pug-language-service` like @johnsoncodehk [suggested](https://github.com/simonhaenisch/prettier-plugin-organize-imports/issues/68#issuecomment-1207762308)

**Comment by simonhaenisch** [comment]
So I just cloned your repro repo, installed `@volar/pug-language-service` as a dev dependency and everything is fine (used `npm` though, not `pnpm`)... not sure what your problem here is? But yeah I should add a note to the readme about this, I guess.

**Comment by Shinigami92** [comment]
I did not understand previously that I need to add `@volar/pug-language-service` in my dev deps 😮
Works 👌
