### ISSUE TITLE
Cannot install version 3.1.1 via npm

### ISSUE THREAD

**Issue by jonz94** [simonhaenisch/prettier-plugin-organize-imports#75]
It seems that the [latest version 3.1.1](https://github.com/simonhaenisch/prettier-plugin-organize-imports/releases/tag/v3.1.1) haven't publish to [npm](https://www.npmjs.com/package/prettier-plugin-organize-imports) yet, so we cannot install it via npm.

<img width="1610" alt="image" src="https://user-images.githubusercontent.com/16042676/188088031-149f84c8-e295-44db-9eb8-5677adcca8a5.png">

**Comment by simonhaenisch** [comment]
Solved, was published into a private registry by accident.

**Comment by jonz94** [comment]
Thanks for the quick response!

I can confirm the issue is fixed.
