### ISSUE TITLE
Automatic removal of entire `import` statements can also delete preceding comment blocks

### ISSUE THREAD

**Issue by jm4rtinez** [simonhaenisch/prettier-plugin-organize-imports#77]
## Summary

If all members of an import declaration are unused, then removing the `import` statement altogether will also remove any regular and doc comments above. This occurs regardless of whitespace and line breaks. This behavior may result in top-level `@module` doc comments being accidentally deleted.

I have only observed this when **all** members of **all** `import` statements are unused. If at least one `import` statement *does* have members in use, this issue doesn't arise - regardless of the import order.

## Reproduction

Using NodeJS with ESModules and TypeScript:

`foo.ts`

```ts
export const foo = 1;
```

`bar.ts`

```ts
/**
 * Module description for `bar`.
 *
 * @module
 */

// regular comment

// another comment

import { foo } from "./foo.js";
```

When the file is formatted, both the `import` statement and all of the comments are deleted.

**Comment by simonhaenisch** [comment]
Ok, can you please raise this issue in the TypeScript repo though, as this would be a bug with the `organizeImports` feature of the language service API. You'll be able to self-fix this by upgrading `typescript` once it's fixed.

In the meantime you could enable the `organizeImportsSkipDestructiveCodeActions` option (see readme) as a temporary workaround.

**Comment by jm4rtinez** [comment]
I will open a separate issue TypeScript, however, I cannot reproduce all of the behavior using only the `Organize Imports` functionality. Specifically, doc comments (formatted between `/**` and `*/` do not get deleted like they do when using the plugin. Only regular comments `//` are deleted.
