### ISSUE TITLE
Upgrade `@volar/vue-typescript` to `v1.0.3`

### ISSUE THREAD

**Issue by Shinigami92** [simonhaenisch/prettier-plugin-organize-imports#78]
`@volar/vue-typescript` is now on `v1.0.3`

Please upgrade and test especially Component imports used in Vue setup lang=ts + template lang=pug

https://www.npmjs.com/package/@volar/vue-typescript

/cc @johnsoncodehk

**Comment by simonhaenisch** [comment]
We currently have these tests, do you think they are sufficient?

https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/8823ca25ec913b27bd18ad67ab75a1cc245cee46/test.js#L105-L168

**Comment by Shinigami92** [comment]
Here is an example of one of my Components:

<details>
<summary>Example</summary>

```vue
<script setup lang="ts">
import DButtonFlatIcon from '@/components/buttons/DButtonFlatIcon.vue';
import DButtonCancel from '@/components/buttons/specific/DButtonCancel.vue';
import DDeleteButton from '@/components/buttons/specific/DButtonDelete.vue';
import { useDialogPluginComponent } from 'quasar';

const { dialogRef, onDialogHide, onDialogOK, onDialogCancel } =
  useDialogPluginComponent();

const props = withDefaults(
  defineProps<{
    title: string;
    text: string;
    context?: any;
  }>(),
  {
    context: null,
  },
);

defineEmits(useDialogPluginComponent.emits);

function onConfirm(): void {
  onDialogOK(props.context);
}

function onCancel(): void {
  onDialogCancel();
}
</script>

<template lang="pug">
QDialog(ref="dialogRef", @hide="onDialogHide")
  QCard
    QToolbar.bg-negative.text-white
      QIcon(name="mdi-cctv", size="md")
      QToolbarTitle {{ title }}
      DButtonFlatIcon(dense, icon="mdi-close", @click="onCancel")
    QCardSection
      .text-body2 {{ text }}
    QCardActions.justify-between
      DButtonCancel(@click="onCancel")
      DDeleteButton(@click="onConfirm")
</template>
```

</details>

When formatting with the newest version currently the first three lines importing my own components (starting with a capital `D`) will get removed.
But they are used in the pug code!

**Comment by simonhaenisch** [comment]
The current [peer dependencies config](https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/master/package.json#L27) allows you to just upgrade to `@volar/vue-typescript` yourself btw, can you just do that and try?

**Comment by johnsoncodehk** [comment]
@Shinigami92 did you have use [@volar/vue-language-plugin-pug](https://www.npmjs.com/package/@volar/vue-language-plugin-pug)? Which required for pug template instead of `@volar/pug-language-service` after `@volar/vue-typescript` v1.0.

**Comment by Shinigami92** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/194876394-f452f451-fa6d-44c0-8176-67c3d41b2b2a.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/7195563/194876458-06caadfc-1ba0-4a16-9c62-558a446d7dcc.png">

**Comment by Shinigami92** [comment]
:scream: I totally missed that I need to try the migration
This gave me the hint to actually read changelog of Volar: https://github.com/johnsoncodehk/volar/issues/1977#issuecomment-1274191660

@johnsoncodehk You definitely need to write this to something that is discoverable like a readme or docu page

But sadly I'm currently not at work and so cannot try it out, will message back in around 2 days when I tried it

**Comment by Shinigami92** [comment]
Okay, now checked with the changes made described by https://github.com/johnsoncodehk/volar/blob/master/CHANGELOG.md#100-alpha0-2022916

Still not working 😕 

So yes, that's definitely a bug or some docu is still missing

**Comment by simonhaenisch** [comment]
@Shinigami92 I'm not sure what to do here... I've added a test case for pug templates and they weren't working before, then I added the extra dependencies `@volar/pug-language-service` and `@volar/vue-language-plugin-pug` and created a `tsconfig.json` like explained in the changelog, but I'm not even sure if the way my tests work it actually picked up the tsconfig 🤷🏻‍♂️ Anyway, doesn't work either.

Since I can't make out the specific issue with prettier-plugin-organize-imports, I'll close this now. If there's still something you think should be solved here and not on Volar's side, you can open another more specific issue, please (:

**Comment by Shinigami92** [comment]
Okay, I will forward this to @johnsoncodehk / Volar
This bug is breaking all my code base and stopping me from upgrading at all

**Comment by Shinigami92** [comment]
Oh my god, you basically already said whats the bug 😆 
Look at these lines:
https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/da2792a9d28d2b2317f2ae91386d1d7b43cdd598/lib/service-host.js#L16-L26

You are fetching the `compilerOptions` and pass the forward
But Volar's new `vueCompilerOptions` are on the same level as `compilerOptions` and therefore doesn't get grabbed and passed forward!
That must be the bug!, Can you please try that out and fix it by forwarding these options as well if they exists?

**Comment by simonhaenisch** [comment]
Hm I just tried but somehow it doesn't fix it :/ I hard-coded the Vue compiler options to include the pug plugin (see [PR](https://github.com/simonhaenisch/prettier-plugin-organize-imports/pull/79/files)), however the test is still failing (removing the import as unused).

**Comment by Shinigami92** [comment]
Okay lets wait on @johnsoncodehk, hopefully he has an idea

**Comment by johnsoncodehk** [comment]
I note that v1 required `prettier-plugin-organize-imports` hardcode `@volar/vue-language-plugin-pug` to `getVueCompilationSettings`, because `prettier-plugin-organize-imports` do not reading project tsconfig setting.

Is it possible to support respect project tsconfig setting?

**Comment by simonhaenisch** [comment]
Yeah I'll do that in the PR just wanted to get it working first. `prettier-plugin-organize-imports` does read the tsconfig already but only retrieves the compiler options (nothing else was needed before).

**Comment by Shinigami92** [comment]
If I can help further please let me know

@johnsoncodehk until then, I now even downgraded Volar VSCode extension as it's unusable for me with
- prettier-plugin-organize-imports >= v3.1.1 (stuck on v3.1.0)
- volar (VSCode ext, vue-tsc and pug plugin) >= v0.40.2 (stuck on v0.40.1)

**Comment by Shinigami92** [comment]
@simonhaenisch 
I have now setup a whole reproducible: https://github.com/Shinigami92/prettier-plugin-organize-imports-issue-78
Please let me know if I can do anything more to get this finally fixed after a month

It's frustrating that I need to pin volar and organize-imports for around a month now and don't getting all volar's new and enhanced stuff

**Comment by simonhaenisch** [comment]
Sorry, I just haven't had the time yet :/ I understand it's frustrating but I also need to do this in my spare time (I make like $2/month from Github Sponsors 😅). Will try to get it done in the next couple days.

**Comment by Shinigami92** [comment]
🙀 I did not sponsor you already monthly? 🙀
That was a mistake on my side... I definitely thought I already have you in my sponsors

**Comment by Shinigami92** [comment]
Fixed 👌

**Comment by simonhaenisch** [comment]
Thanks a lot ❤️ Also good news, I've actually finished the PR. I just need to review it again tmrw because it's too late now, so I don't trust myself right now 😅

**Comment by simonhaenisch** [comment]
@Shinigami92 can you try with `3.2.0` now?

**Comment by Shinigami92** [comment]
WORKS
