### ISSUE TITLE
What is the order it sorts by?

### ISSUE THREAD

**Issue by mesqueeb** [simonhaenisch/prettier-plugin-organize-imports#81]
The Readme only says it sorts the imports but doesn't explain how it sorts them, by what kind of order? 

Alphabetically?
External first?
What about monorepo packages?

Would love to see these answers in the Readme : )

**Comment by simonhaenisch** [comment]
It sorts them according to the TypeScript Language Service API's `organizeImports` method which is the same as calling the "Organize Imports" action in VS Code. I don't even know the specifics of how it sorts the imports (i think it's purely alphabetically?) and I frankly don't care (: Also, how it does it depends on your version of the `typescript` peer dependency, i.e. different TS versions might do it (slightly) differently 🤷🏻‍♂️ I also don't care about that either as long as I get the same order every time I prettify.

If you care about the order, you're in the wrong place with this plugin 😅
