### ISSUE TITLE
Cache performance issue

### ISSUE THREAD

**Issue by dgruszcz** [simonhaenisch/prettier-plugin-organize-imports#90]
https://github.com/simonhaenisch/prettier-plugin-organize-imports/blob/3cceaf4a0c97f5a438f0490901590dbdc590aa3b/lib/get-compiler-options.js#L24

memoize for getCompilerOptions uses path of the formatted file as a cache key instead of the tsconfig file path (as in v3.1.1). It causes that the tsconfig file content is parsed for each formatted file regardless if they are related to same tsconfig file or not. This adds unneccessary constant delay and for a large number of files it quickly adds up.

**Comment by simonhaenisch** [comment]
Cool thanks for reporting yeah will need to get that fixed.
