### ISSUE TITLE
Ability to add aliases

### ISSUE THREAD

**Issue by gkiely** [simonhaenisch/prettier-plugin-organize-imports#92]
In an application I'm working on we use aliases for certain paths, for example:

```ts
import * as appStyles from 'app/App.css';
import { darkTheme, lightTheme } from 'app/theme.css'
import { timeouts } from 'utils/constants';
```

Unfortunately these get moved to the top, above libraries, unless they have been separated by a new line.

Possible solutions:
1. Allow pulling in aliases from vite.config.ts and putting those below library imports
2. Allow specifying aliases in prettierconfig
3. Allow specifying an import order in prettierconfig

**Comment by simonhaenisch** [comment]
Sorry, out of scope for this plugin, it strictly does what the TypeScript compiler API method `organizeImports` does.
