### ISSUE TITLE
Does not work with Prettier 3.0

### ISSUE THREAD

**Issue by Zamiell** [simonhaenisch/prettier-plugin-organize-imports#95]
Prettier 3.0 looks to be [coming pretty soon](https://github.com/prettier/prettier/issues/13142).

The [combability guide is here](https://github.com/prettier/prettier/wiki/How-to-migrate-my-plugin-to-support-Prettier-v3%3F), for reference.

This issue is mostly to raise awareness. Is this plugin already compatible?

Additionally, having this plugin as an ESM module would be nice, which Prettier 3.0 now allows.

**Comment by simonhaenisch** [comment]
Thanks, I'll try to find some time for it. Switching to ESM would be nice but I assume it would break compatibility with older Prettier versions so I'd wait with that for a while.

**Comment by bartlangelaan** [comment]
Prettier 3 was released today!

**Comment by curtvict** [comment]
It seems that prettier-plugin-organize-imports` is not compatible with Prettier 3, unfortunately. I don't see any errors being thrown, but the plugin just seems to have stopped working.

**Comment by littlebtc** [comment]
I think this breaks as [they renamed and moved all parsers](https://prettier.io/blog/2023/07/05/3.0.0.html#npm-package-file-structures-changed-12740httpsgithubcomprettierprettierpull12740-by-fiskerhttpsgithubcomfisker-13530httpsgithubcomprettierprettierpull13530-by-fiskerhttpsgithubcomfisker-14570httpsgithubcomprettierprettierpull14570-by-fiskerhttpsgithubcomfisker).

Fixing it may be easy but maybe more issues are coming.

**Comment by nbouvrette** [comment]
@simonhaenisch I had to downgrade Prettier today because your plugin is so useful, I can no longer code without it :) Do you have any idea when you are planning to support Prettier 3+

**Comment by simonhaenisch** [comment]
Hey thanks for the comment, so you're confirming it's not compatible at the moment, right?

I only checked the migration guide so far and nothing looked breaking wrt this plugin, so I'll have to take a closer look.

**Comment by nbouvrette** [comment]
@simonhaenisch yes as soon as I upgraded it stopped working.. no errors, nothing

**Comment by aronmal** [comment]
> Hey thanks for the comment, so you're confirming it's not compatible at the moment, right?

Works for me. My `prettier.config.js`:

```
module.exports = {
  semi: false,
  plugins: [
    "prettier-plugin-organize-imports",
    "prettier-plugin-tailwindcss", // MUST come last
  ],
}
```

I used the [trivago sort plugin](https://github.com/trivago/prettier-plugin-sort-imports) in another project, there I also had to have tailwind last. With prettier `2.8.8` and this organize imports plugin it somehow needed to be the other way around (tailwind first). But with `3.0` tailwind last AND "Developer: Reload Window" in VSCode so the config gets reloaded  (tricked me first hand when both plugins didn't worked after updating the packages with pnpm).

**Comment by simonhaenisch** [comment]
Thanks @aronmal!

Reloading the window is what I was going to suggest to @nbouvrette as well. I've had this Prettier binary caching issue in VS Code as well before.

I just tried upgrading the project and other than some adjustments for the test execution (which use the Prettier API programmatically that is now async) I didn't have to change anything to make them pass again.

However I just saw @littlebtc's comment about the renaming of parsers and yeah it's actually surprising that all the tests are passing 🤔

**Comment by simonhaenisch** [comment]
Ah ok figured it out, they have extensively defined `exports` in their `package.json` to make sure the old import paths still work as well (see https://unpkg.com/browse/prettier@3.0.0/package.json).

**Comment by simonhaenisch** [comment]
Please drop a comment if sth doesn't work. But first try to use Prettier programmatically (`npx prettier -w some-file.js`) to make sure it's not just a problem with the VS Code extension 🙏

**Comment by scottwillmoore** [comment]
It does work for with both `npx prettier` and the Visual Studio Code extension with both `3.2.2` and the latest commit [`b15df6a`](https://github.com/simonhaenisch/prettier-plugin-organize-imports/commit/b15df6ae8dfb548df2065bbab9d75fb9d7304899). I installed the package as a Git repository to check that it worked. However, it appears to only work when I add this plugin in to the prettier configuration. The plugin discovery doesn't appear to work? I think this might be a separate problem, maybe upstream?

The plugin should probably be pushed to `npm` at some point. I expect the major version with also need to be bumped, as this plugin will cease to work with Prettier `2.x.x`?

**Comment by sven-meyer-wetter-com** [comment]
Yes, please make a new npm release.

**Comment by spdiswal** [comment]
> However, it appears to only work when I add this plugin in to the prettier configuration. The plugin discovery doesn't appear to work? I think this might be a separate problem, maybe upstream?

@scottwillmoore Plugin discovery was removed in Prettier 3 (https://github.com/prettier/prettier/pull/14759) :slightly_smiling_face:

**Comment by scottwillmoore** [comment]
@spdiswal Ah I see! Thanks for the heads up.

**Comment by Zamiell** [comment]
#102

**Comment by nbouvrette** [comment]
Just to confirm, adding  this in my `.prettierrc` did the trick:

```yaml
plugins:
  - prettier-plugin-organize-imports
```

Thanks @spdiswal

**Comment by simonhaenisch** [comment]
Yes exactly, I just haven't published because basically none of the changes since then would change the actual published code.

Regarding the readme, yes I'll get that updated, thanks (:

**Comment by hisham** [comment]
I'm getting this error in VSCode prettier plugin: 

```
["DEBUG" - 9:45:30 AM] Local prettier module path: '/Users/hisham/src/ess-app/node_modules/prettier'
["DEBUG" - 9:45:30 AM] Using prettier version 3.0.0
["ERROR" - 9:45:30 AM] Error resolving prettier configuration for /Users/hisham/src/ess-app
["ERROR" - 9:45:30 AM] Invalid host defined options
```

However running prettier from the command line works...

**Comment by aronmal** [comment]
> Invalid host defined options

@hisham I think you got your answer there. But if you think it has to do with this plugin and the migration from prettier 2.x to 3, please provide your prettier config file.

Otherwise open a new issue with steps to reproduce the error.

**Comment by hisham** [comment]
Hi @aronmal - yep it has nothing to do with your plugin. Was a VSCode and prettier vscode extension issue. Thank you :)
