### ISSUE TITLE
[Feature request] Only remove unused imports

### ISSUE THREAD

**Issue by agreedSkiing** [simonhaenisch/prettier-plugin-organize-imports#99]
Would it be possible to have the plugin only remove unused imports?

This would make it compatible with https://github.com/trivago/prettier-plugin-sort-imports where you can specify the import ordering.

**Comment by simonhaenisch** [comment]
Sry, not possible, the TypeScript API doesn't offer any option for that (just `skipDestructiveCodeActions`).

Still standing by my point that you really shouldn't care about the order of imports 🤓

**Comment by agreedSkiing** [comment]
> Sry, not possible, the TypeScript API doesn't offer any option for that (just `skipDestructiveCodeActions`).
> 
> Still standing by my point that you really shouldn't care about the order of imports 🤓 (if you tend to OCD then think of simple alphabetic ordering as just another form of order 😬)

I do not care for the said ordering, but most of our team does that why the request :/
